export const currentAffairs = [
  {
    id: 9,
    date: "01 Oct 2026",
    category: "National",
    title: "Gandhi Jayanti 2 Oct Special: स्वच्छ भारत को 12 साल",
    summary: "2 अक्टूबर को गांधी जयंती + स्वच्छ भारत मिशन (2014) की 12वीं वर्षगांठ। static GK: जन्म 2 Oct 1869 पोरबंदर, ‘My Experiments with Truth’ आत्मकथा।",
    tag: "Hot",
    source: "mkgandhi.org",
    link: "https://www.mkgandhi.org",
  },
  {
    id: 10,
    date: "01 Oct 2026",
    category: "Awards",
    title: "Nobel Prize 2026 घोषणाएं 5 Oct से शुरू",
    summary: "पहले Medicine, फिर Physics, Chemistry, Literature, Peace, Economics। पहला Nobel 1901 में — भारतीय विजेता (टैगोर 1913, रमन 1930) revision करें।",
    tag: "Exam",
    source: "nobelprize.org",
    link: "https://www.nobelprize.org",
  },
  {
    id: 11,
    date: "01 Oct 2026",
    category: "Economy",
    title: "RBI MPC October बैठक पर नजर: Repo Rate 6.5%",
    summary: "पिछली 5 बैठकों से रेपो रेट 6.5% स्थिर। MPC में 6 सदस्य (3 RBI + 3 सरकार)। महंगाई लक्ष्य 4% ±2% — Economy revision must।",
    tag: "Exam",
    source: "rbi.org.in",
    link: "https://www.rbi.org.in",
  },
  {
    id: 12,
    date: "01 Oct 2026",
    category: "Study",
    title: "October Week-1 Current Affairs PDF + September Revision Live",
    summary: "नए महीने की शुरुआत September revision से करें। Week-1 PDF (Hindi) Free — Study Material section में Download करें।",
    tag: "New",
    source: "pib.gov.in",
    link: "https://pib.gov.in",
  },
  {
    id: 1,
    date: "30 Sep 2026",
    category: "National",
    title: "Digital India Land Records 2.0: सभी राज्यों में ULPIN लागू",
    source: "dolr.gov.in",
    link: "https://dolr.gov.in",
    summary: "सरकार ने सभी ग्रामीण भूमि रिकॉर्ड को 14-अंकीय ULPIN से जोड़ने का लक्ष्य मार्च 2027 तक रखा। पटवारी रिकॉर्ड अब ऑनलाइन e-Dharti पोर्टल पर।",
    tag: "Hot",
  },
  {
    id: 2,
    date: "29 Sep 2026",
    category: "Economy",
    title: "RBI Repo Rate 6.5% स्थिर, GDP Growth अनुमान 7.1%",
    source: "rbi.org.in",
    link: "https://www.rbi.org.in",
    summary: "RBI MPC ने लगातार 5वीं बार रेपो रेट स्थिर रखा। महंगाई अनुमान 4.3% — SSC/Railway Economy सेक्शन के लिए महत्वपूर्ण।",
    tag: "Exam",
  },
  {
    id: 3,
    date: "28 Sep 2026",
    category: "Sports",
    title: "Asian Games 2026: भारत 28 Gold के साथ तीसरे स्थान पर",
    source: "aichi-nagoya2026.org",
    link: "https://www.aichi-nagoya2026.org",
    summary: "एशियाई खेलों में भारत ने एथलेटिक्स और शूटिंग में रिकॉर्ड पदक जीते। GK में पदक तालिका + शुभंकर याद रखें।",
    tag: "GK",
  },
  {
    id: 4,
    date: "27 Sep 2026",
    category: "Science",
    title: "ISRO Gaganyaan G-1 Uncrewed Mission सफल",
    source: "isro.gov.in",
    link: "https://www.isro.gov.in",
    summary: "ISRO ने मानव रहित G-1 मिशन पूरा किया, 2027 में मानव मिशन का रास्ता साफ। Vyommitra रोबोट की टेस्टिंग सफल रही।",
    tag: "Hot",
  },
  {
    id: 5,
    date: "26 Sep 2026",
    category: "Polity",
    title: "One Nation One Election: कोविंद समिति की सिफारिशों पर विधेयक",
    source: "eci.gov.in",
    link: "https://www.eci.gov.in",
    summary: "लोकसभा + विधानसभा एक साथ चुनाव का प्रस्ताव। अनुच्छेद 83, 172 में संशोधन की जरूरत — UPSC Polity के लिए टॉपिक।",
    tag: "UPSC",
  },
  {
    id: 6,
    date: "25 Sep 2026",
    category: "Environment",
    title: "3 नए Ramsar Sites: भारत में कुल 93 वेटलैंड",
    source: "ramsar.org",
    link: "https://www.ramsar.org",
    summary: "मध्य प्रदेश और तमिलनाडु के 3 स्थल रामसर सूची में। पर्यावरण + मैपिंग प्रश्नों में पूछा जाता है।",
    tag: "GK",
  },
  {
    id: 7,
    date: "24 Sep 2026",
    category: "Awards",
    title: "National Teachers Award 2026: 82 शिक्षक सम्मानित",
    source: "education.gov.in",
    link: "https://nationalteacheraward.education.gov.in",
    summary: "राष्ट्रपति ने नवाचारपूर्ण शिक्षण के लिए 82 शिक्षकों को सम्मानित किया। शिक्षा मंत्रालय की नई mentoring योजना भी लॉन्च।",
    tag: "New",
  },
  {
    id: 8,
    date: "23 Sep 2026",
    category: "International",
    title: "India–EU Free Trade Agreement का अंतिम दौर",
    source: "commerce.gov.in",
    link: "https://commerce.gov.in",
    summary: "भारत-EU FTA वार्ता अंतिम चरण में। टैरिफ, डेटा सुरक्षा और कृषि सब्सिडी मुख्य मुद्दे — Current Affairs Mains Point।",
    tag: "Exam",
  },
];

export const jobs = [
  {
    id: 1,
    org: "SSC GD Constable 2026",
    posts: "39,481 पद",
    qual: "10वीं पास",
    lastDate: "14 Oct 2026",
    fee: "Gen/OBC ₹100 • SC/ST/Women Free",
    age: "18–23 वर्ष",
    status: "Apply Online",
    hot: true,
    link: "https://ssc.gov.in",
  },
  {
    id: 2,
    org: "RRB NTPC (Railway) 2026",
    posts: "11,558 पद",
    qual: "12वीं / Graduate",
    lastDate: "27 Oct 2026",
    fee: "Gen ₹500 • SC/ST/Women ₹250 (refundable)",
    age: "18–33 वर्ष",
    status: "Apply Online",
    hot: true,
    link: "https://www.rrbapply.gov.in",
  },
  {
    id: 3,
    org: "UP Police Constable भर्ती",
    posts: "19,220 पद",
    qual: "12वीं पास",
    lastDate: "31 Oct 2026",
    fee: "सभी वर्ग ₹400",
    age: "18–25 वर्ष (छूट नियमानुसार)",
    status: "Apply Online",
    hot: true,
    link: "https://uppbpb.gov.in",
  },
  {
    id: 4,
    org: "IBPS PO/MT 2026",
    posts: "5,208 पद",
    qual: "Graduate (किसी भी stream)",
    lastDate: "21 Oct 2026",
    fee: "Gen/OBC ₹850 • SC/ST ₹175",
    age: "20–30 वर्ष",
    status: "Apply Online",
    hot: false,
    link: "https://www.ibps.in",
  },
  {
    id: 5,
    org: "UPSC CSE 2027 Notification",
    posts: "~1,056 पद (संभावित)",
    qual: "Graduate",
    lastDate: "Jan 2027 (Expected)",
    fee: "Gen/OBC ₹100 • SC/ST/Women Free",
    age: "21–32 वर्ष",
    status: "Coming Soon",
    hot: false,
    link: "https://upsc.gov.in",
  },
  {
    id: 6,
    org: "CTET January 2027",
    posts: "Eligibility Test",
    qual: "B.Ed / D.El.Ed",
    lastDate: "Dec 2026 (Expected)",
    fee: "Gen ₹1000 • SC/ST ₹500",
    age: "No Age Limit",
    status: "Coming Soon",
    hot: false,
    link: "https://ctet.nic.in",
  },
];

export const exams = [
  {
    id: 1,
    name: "UPSC CSE Prelims 2026",
    date: "24 May 2026 (Done) • Mains Sep 2026",
    pattern: "GS Paper-I + CSAT • 200-200 Marks",
    syllabus: "History, Polity, Geography, Economy, Env, Sci-Tech + Current Affairs",
  },
  {
    id: 2,
    name: "SSC CGL 2026",
    date: "Tier-I: Aug–Sep 2026",
    pattern: "100 Q • 200 Marks • 60 min • Neg. 0.50",
    syllabus: "Quant, Reasoning, English, GK",
  },
  {
    id: 3,
    name: "RRB NTPC CBT-1",
    date: "Nov–Dec 2026 (Expected)",
    pattern: "100 Q • 100 Marks • 90 min",
    syllabus: "Maths 30 + Reasoning 30 + GK 40",
  },
  {
    id: 4,
    name: "NEET UG 2027",
    date: "May 2027 (Expected)",
    pattern: "200 Q (180 attempt) • 720 Marks • NCERT Based",
    syllabus: "Physics, Chemistry, Biology (XI + XII)",
  },
  {
    id: 5,
    name: "CTET / UPTET",
    date: "Jan–Feb 2027",
    pattern: "150 Q • 150 Marks • No Negative",
    syllabus: "CDP, Hindi, English, Maths, EVS",
  },
  {
    id: 6,
    name: "CUET UG 2027",
    date: "May 2027",
    pattern: "CBT • Subject + GAT + Language",
    syllabus: "NCERT XII + General Aptitude",
  },
];

export const studyMaterial = [
  { id: 9, title: "October 2026 Week-1 Current Affairs (Hindi)", pages: "25 Pages", type: "PDF", downloads: "New", link: "https://pib.gov.in" },
  { id: 1, title: "NCERT History Notes (Class 6–12) Hindi", pages: "220 Pages", type: "PDF", downloads: "48.2K", link: "https://ncert.nic.in/textbook.php" },
  { id: 2, title: "Indian Polity – Laxmikanth सारांश", pages: "180 Pages", type: "PDF", downloads: "39.7K", link: "https://www.india.gov.in/my-government/constitution-india" },
  { id: 3, title: "Geography Maps + Rivers + Soils Chart", pages: "95 Pages", type: "PDF", downloads: "31.5K", link: "https://surveyofindia.gov.in" },
  { id: 4, title: "Maths Formula Book – SSC/Railway", pages: "120 Pages", type: "PDF", downloads: "52.1K", link: "https://ssc.gov.in" },
  { id: 5, title: "English Grammar Rules + 5000 Vocab", pages: "150 Pages", type: "PDF", downloads: "27.8K", link: "https://ncert.nic.in/textbook.php" },
  { id: 6, title: "Lucent GK One-Liner 5000 प्रश्न", pages: "300 Pages", type: "PDF", downloads: "61.4K", link: "https://pib.gov.in" },
  { id: 7, title: "UP GK Special – परीक्षा दृष्टि", pages: "80 Pages", type: "PDF", downloads: "22.3K", link: "https://up.gov.in" },
  { id: 8, title: "Current Affairs Monthly – Sep 2026", pages: "60 Pages", type: "PDF", downloads: "18.9K", link: "https://pib.gov.in" },
];

export const gkQuestions = [
  {
    q: "भारत का राष्ट्रीय पशु कौन है?",
    options: ["शेर", "बंगाल टाइगर", "हाथी", "तेंदुआ"],
    answer: 1,
    explain: "बंगाल टाइगर (Panthera tigris) 1973 से राष्ट्रीय पशु है।",
  },
  {
    q: "संविधान का अनुच्छेद 370 किससे संबंधित था?",
    options: ["आपातकाल", "जम्मू-कश्मीर विशेष दर्जा", "शिक्षा का अधिकार", "संपत्ति का अधिकार"],
    answer: 1,
    explain: "अनु. 370 जम्मू-कश्मीर को विशेष दर्जा देता था, अगस्त 2019 में निष्प्रभावी।",
  },
  {
    q: "‘जनगणना 2011’ के अनुसार भारत की साक्षरता दर?",
    options: ["65.4%", "74.04%", "82.1%", "69.3%"],
    answer: 1,
    explain: "2011 जनगणना: कुल साक्षरता 74.04% (पुरुष 82.14%, महिला 65.46%)।",
  },
  {
    q: "सबसे लंबी नदी (भारत में बहने वाली) कौन सी है?",
    options: ["यमुना", "गोदावरी", "गंगा", "ब्रह्मपुत्र"],
    answer: 2,
    explain: "गंगा ~2525 km — भारत में सबसे लंबी नदी प्रणाली।",
  },
  {
    q: "RBI की स्थापना कब हुई?",
    options: ["1935", "1947", "1950", "1921"],
    answer: 0,
    explain: "RBI Act 1934 के तहत 1 अप्रैल 1935 को स्थापना।",
  },
  {
    q: "पानीपत की पहली लड़ाई (1526) किसके बीच हुई?",
    options: ["अकबर–हेमू", "बाबर–इब्राहिम लोदी", "शेरशाह–हुमायूं", "मराठा–अब्दाली"],
    answer: 1,
    explain: "बाबर ने इब्राहिम लोदी को हराकर मुगल साम्राज्य की नींव रखी।",
  },
  {
    q: "भारत का सबसे बड़ा राज्य (क्षेत्रफल) कौन है?",
    options: ["मध्य प्रदेश", "महाराष्ट्र", "उत्तर प्रदेश", "राजस्थान"],
    answer: 3,
    explain: "राजस्थान ~342,239 sq km क्षेत्रफल में सबसे बड़ा राज्य।",
  },
  {
    q: "ओलंपिक में भारत का पहला व्यक्तिगत स्वर्ण किसने जीता?",
    options: ["पी.वी. सिंधु", "अभिनव बिंद्रा", "नीरज चोपड़ा", "मैरी कॉम"],
    answer: 1,
    explain: "अभिनव बिंद्रा — बीजिंग 2008, 10m एयर राइफल।",
  },
  {
    q: "‘सत्यमेव जयते’ कहाँ से लिया गया है?",
    options: ["ऋग्वेद", "मुण्डकोपनिषद", "भगवद्गीता", "अर्थशास्त्र"],
    answer: 1,
    explain: "मुण्डकोपनिषद से — राष्ट्रीय आदर्श वाक्य।",
  },
  {
    q: "GST किस संविधान संशोधन से लागू हुआ?",
    options: ["100वां", "101वां", "102वां", "103वां"],
    answer: 1,
    explain: "101वां संशोधन 2016, GST 1 जुलाई 2017 से लागू।",
  },
  {
    q: "महात्मा गांधी का जन्म कब और कहाँ हुआ?",
    options: ["2 Oct 1869, पोरबंदर", "15 Aug 1872, अहमदाबाद", "2 Oct 1875, राजकोट", "26 Jan 1869, सूरत"],
    answer: 0,
    explain: "2 अक्टूबर 1869, पोरबंदर (गुजरात) — 2026 में 157वीं जयंती।",
  },
  {
    q: "पहला Nobel Prize किस वर्ष दिया गया?",
    options: ["1895", "1901", "1913", "1905"],
    answer: 1,
    explain: "1901 से शुरुआत; अल्फ्रेड नोबेल की वसीयत (1895) के अनुसार।",
  },
  {
    q: "स्वच्छ भारत मिशन कब लॉन्च हुआ?",
    options: ["15 Aug 2014", "2 Oct 2014", "26 Jan 2015", "2 Oct 2015"],
    answer: 1,
    explain: "2 अक्टूबर 2014, गांधी जयंती के दिन लॉन्च।",
  },
  {
    q: "RBI की MPC (Monetary Policy Committee) में कितने सदस्य होते हैं?",
    options: ["5", "6", "7", "9"],
    answer: 1,
    explain: "6 सदस्य — 3 RBI से, 3 सरकार द्वारा नियुक्त।",
  },
];

export const admitCards = [
  { id: 1, exam: "SSC GD Constable PET/PST 2026", examDate: "15 Oct 2026", status: "Released", site: "ssc.gov.in", link: "https://ssc.gov.in" },
  { id: 2, exam: "RRB NTPC CBT-1 2026", examDate: "Nov 2026", status: "Soon", site: "rrbapply.gov.in", link: "https://www.rrbapply.gov.in" },
  { id: 3, exam: "UP Police Written Exam", examDate: "Dec 2026", status: "Soon", site: "uppbpb.gov.in", link: "https://uppbpb.gov.in" },
  { id: 4, exam: "IBPS PO Prelims 2026", examDate: "04–05 Oct 2026", status: "Released", site: "ibps.in", link: "https://www.ibps.in" },
  { id: 5, exam: "CTET Sep 2026", examDate: "21 Sep 2026 (Done)", status: "Closed", site: "ctet.nic.in", link: "https://ctet.nic.in" },
  { id: 6, exam: "UPSC Mains 2026", examDate: "22 Aug 2026 (Done)", status: "Closed", site: "upsc.gov.in", link: "https://upsc.gov.in" },
];

export const results = [
  { id: 1, exam: "SSC CGL Tier-I 2026", declared: "28 Sep 2026", cutoff: "Gen ~153 • OBC ~145", status: "Declared", link: "https://ssc.gov.in" },
  { id: 2, exam: "UP Board Class 10 Compartment", declared: "25 Sep 2026", cutoff: "Pass % – 89.4%", status: "Declared", link: "https://upmsp.edu.in" },
  { id: 3, exam: "Railway Group D PET Result", declared: "20 Sep 2026", cutoff: "Zone-wise PDF", status: "Declared", link: "https://indianrailways.gov.in" },
  { id: 4, exam: "IBPS Clerk Prelims 2026", declared: "Expected Oct 2026", cutoff: "—", status: "Soon", link: "https://www.ibps.in" },
  { id: 5, exam: "CTET Sep 2026", declared: "Expected Oct 2026", cutoff: "Gen 60% • SC/ST 55%", status: "Soon", link: "https://ctet.nic.in" },
  { id: 6, exam: "NEET UG Counselling Round-2", declared: "27 Sep 2026", cutoff: "MCC Seat Allotment", status: "Declared", link: "https://mcc.nic.in" },
];

export const tickerItems = [
  "SSC GD Last Date नजदीक — 14 Oct 2026, जल्द Apply करें",
  "Gandhi Jayanti Special Notes + Quiz Live",
  "October Week-1 Current Affairs PDF Free Download",
  "Nobel Prize 2026 घोषणाएं 5 Oct से",
  "RRB NTPC 11,558 पद — Apply Online जारी",
  "IBPS PO Prelims Admit Card Released",
];
